version: '3.8'

services:
  api:
    build: .
    container_name: social-network-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - social-network

  db:
    image: postgres:14-alpine
    container_name: social-network-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - social-network

networks:
  social-network:
    driver: bridge

volumes:
  pgdata: